name: Run Tests and Compare Coverage
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      TESTING_DB_URL: '${{ secrets.TESTING_DB_URL }}'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
      - name: Setup Node.js
        uses: actions/setup-node@v2
      
      - name: Install dependencies
        run: npm install
      
      - name: Run Jest tests with coverage
        run: npm test -- --coverage --coverageReporters=json-summary

      - name: Print test coverage of statements
        run: |
          coverage_pct=$(jq -r '.total.statements.pct' coverage/coverage-summary.json)
          echo "Percentage of statements coverage: $coverage_pct"
          
          if (( $(echo "$coverage_pct > 95" | bc -l) )); then
            echo "Test coverage is greater than 95%."
          else
            echo "Test coverage is less than or equal to 95%."
            exit 1
          fi
  prettier-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Check code formatting with Prettier
        run: npm run format-check